[package]
name = "abc-game"
version = "0.1.0"
authors = ["jessie <jessie.varela6@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "0.3"
actix-web = "3"
env_logger = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"